Resolve of Issue #31.
rayceramsay/music-trivia pull request #37
Opened 2023-11-29 20:54 UTC by Artakarak

We now can attain a score within our
RoundView and LoadableGamesView.

2023-11-29 21:35 UTC, rayceramsay requested changes
Nice job Artak! Good work on updating the tests as well, those are easy to forget about. Just a couple of notes:

It would appear that the score label displays the same score as the previously played game for the first round when you create a new game (e.g. if I have a score in the previous game of 2 then go to the menu and create a new game, it will say I have a score of 2). This will require a minor fix with updating the RoundState on game creation to set the score to the proper value (i.e. 0).

Going forward, making your commit messages a bit more descriptive would help those reviewing your PRs. It doesn't have to be anything crazy, but for example, I don't really know what `Final touches, fully done.` is referencing. If you said something like `Added score label to RoundView` instead, then I would have a better idea of what the commit was for. This is especially useful for maintenance in the long run as it makes it easier to figure out where bugs come from if they arise.

2023-11-29 21:35 UTC, rayceramsay commented on test/use_case/get_loadable_games/load_game/LoadGameInteractorTest.java
> +package use_case.get_loadable_games.load_game;
It looks like you accidentally moved the load_game folder in test/use_case to be under get_loadable_games. If you could move it back to be at the same level as the others that would be great.

2023-11-29 22:49 UTC, Artakarak commented
> Nice job Artak! Good work on updating the tests as well, those are easy to forget about. Just a couple of notes:
> 
> It would appear that the score label displays the same score as the previously played game for the first round when you create a new game (e.g. if I have a score in the previous game of 2 then go to the menu and create a new game, it will say I have a score of 2). This will require a minor fix consisting of updating the RoundState on game creation to set the score to the proper value (i.e. 0).
> 
> Going forward, making your commit messages a bit more descriptive would help those reviewing your PRs. It doesn't have to be anything crazy, but for example, I don't really know what `Final touches, fully done.` is referencing. If you said something like `Added score label to RoundView` instead, then I would have a better idea of what the commit was for. This is especially useful for maintenance in the long run as it makes it easier to figure out where bugs come from if they arise.

Yeah Rayce that's my bad. Thank you for making me 1% better today. I have fixed the remaining error that you mentioned, let me know of anything else that you may catch!

2023-11-30 01:08 UTC, rayceramsay approved these changes
Works very well! 🙂

2023-11-30 02:52 UTC, NickinAction approved these changes
Looks good and works well!

2023-11-30 22:49 UTC, merged