32 improve documentation with JavaDoc
rayceramsay/music-trivia pull request #42
Opened 2023-12-01 06:06 UTC by ARoy667

This is an ongoing PR which I will continue to push to as we add more files to our codebase. So far I have added JavaDoc for virtually every public interface and their implementing classes/methods, as well as for constructors for every class that has been pushed to Main. 
At the same time, I have also been handling Issue 30 (refactor code for consistent formatting) by trying to catch any discrepancies and following a consistent solution for spacing, empty lines, spacing between braces, etc.

Feel free to suggest any edits for the descriptions I added or if I missed anything :)

2023-12-01 08:01 UTC, rayceramsay commented on src/entity/CommonGame.java
> +     * Subtracts one from current score.
```suggestion
     * Subtracts one from current lives.
```

2023-12-01 08:08 UTC, rayceramsay commented on src/view/LoadableGamesViewFactory.java
> +     * Creates instance pf LoadGameController
```suggestion
     * Creates an instance of LoadGameController
```

2023-12-01 08:15 UTC, rayceramsay commented
Wow, this is awesome Aabha! Thanks for doing this!

Just a friendly reminder to merge main into this branch every so often so that there aren't big conflicts from things like documenting files that got deleted/significantly changed or stuff like that.

2023-12-01 14:15 UTC, ethanmcf approved these changes
Damn this a lot of comments, good job!

2023-12-01 17:17 UTC, NickinAction approved these changes
Looks good!

2023-12-01 21:53 UTC, ethanmcf requested changes
Just want to remove the keys from api.env before we merge to main

2023-12-02 18:43 UTC, ARoy667 commented
I saw that Rayce has added JavaDoc comments to his existing SQLite database PR so if that is the only thing left to merge into main I think we should be good to merge this as well

2023-12-03 03:32 UTC, Artakarak approved these changes
Just as we needed.

2023-12-03 17:47 UTC, merged